#!/usr/bin/env bash

netstat -ano | grep LISTENING | while read -r line
do
    pid=$(echo "$line" | awk '{print $5}')
    program=$(tasklist /FI "PID eq $pid" /FO CSV /NH | cut -d',' -f1 | tr -d '"')
    echo "$line $pid/$program"
done
